### ISSUE TITLE
[Android Bootcamp Observers] Review simple tip calculator app

### ISSUE THREAD

**Issue by safiume** [safiume/simple-tipcalc#1]
I completed the tip calculator, and it's ready for review. I have a question about how I got the code to fire the button that's clicked on submit, was I supposed to name it in a more OOP manner and access it in a more method like or OOPish like manner? /cc @nesquena
I didn't complete any optional stories. It took me a few days to get this coded and find the correct java syntax which only started to gel when I was working with the debugger.

**Comment by nesquena** [comment]
:+1: Looks good overall. I have provided a detailed [Project 1 Feedback Guide here](https://gist.github.com/nesquena/2e76670cfb4e751caf95) which covers the most common issues with this submitted project. Read through the feedback guide point-by-point to determine how you could improve your submission. You should consider going back and implementing applicable feedback as well. Keep in mind that one of the most important parts of Android development is learning the correct patterns and conventions.

Hopefully this has given you a first sense of the RelativeLayout which is a very powerful layout system, probably one of the best responsive-first layout systems available across web and mobile platforms. 

The next assignment will build on top of the first concepts introduced here and will also introduce networking, api use, handling remote images and navigating between activities.

If you have any particular questions about the assignment in general or on any of the feedback, feel free to reply here or post on the observer google groups.

> was I supposed to name it in a more OOP manner and access it in a more method like or OOPish like manner?

Actually, your current approach is fine.

**Comment by safiume** [comment]
This one is pretty old. I'm closing it.
